In [1]:
from getData import getData
import pandas as pd
import numpy as np

In [2]:
data = getData()

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52275 entries, 0 to 52274
Data columns (total 7 columns):
category         52275 non-null object
categoryID       52275 non-null int64
dealID           52275 non-null int64
purchaseDate     52275 non-null object
purchaseID       52275 non-null int64
purchaseTotal    52275 non-null int64
userID           52275 non-null int64
dtypes: int64(5), object(2)
memory usage: 2.8+ MB

In [4]:
data = data.set_index(["userID","category"])

In [5]:
user_item=data.groupby(["userID","category"])["categoryID"].count().unstack(fill_value=0)
del data

In [6]:
user_item.head()

category,Automoviles,Belleza,Boletos aéreos,Campamentos,Caracas,Carnavales,Crecimiento Personal,Cupones para Navidad,Deportes y Fitness,Día de las madres,...,Montañas,Obsequios,Planes Internacionales,Playas,Productos,Salud,San Valentín,Selva,Semana Santa,Servicios Profesionales
userID,,,,,,,,,,,,,,,,,,,,,
13,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
103,0,1,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
110,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
131,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
197,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
user_item.columns=user_item.columns.str.replace(" ","_")
user_item.columns=user_item.columns.str.replace("á","a")
user_item.columns=user_item.columns.str.replace("é","e")
user_item.columns=user_item.columns.str.replace("í","i")
user_item.columns=user_item.columns.str.replace("ó","o")
user_item.columns=user_item.columns.str.replace("ú","u")
user_item.columns=user_item.columns.str.replace("ñ","n")

In [8]:
user_item.columns.values

array(['Automoviles', 'Belleza', 'Boletos_aereos', 'Campamentos',
       'Caracas', 'Carnavales', 'Crecimiento_Personal',
       'Cupones_para_Navidad', 'Deportes_y_Fitness', 'Dia_de_las_madres',
       'Dia_del_padre', 'Entretenimiento_y_Cultura', 'Extremo',
       'Festejos_y_Celebraciones', 'Full_Day', 'Fundaciones',
       'Gastronomia', 'Hoteles_Caracas', 'Mascotas', 'Montanas',
       'Obsequios', 'Planes_Internacionales', 'Playas', 'Productos',
       'Salud', 'San_Valentin', 'Selva', 'Semana_Santa',
       'Servicios_Profesionales'], dtype=object)